# Site Settings
title: Selçuk Kılınç | Science, Technology & Education Researcher
name: "Selçuk Kılınç"
description: "PhD-trained science educator and software engineer fusing research with technology to elevate STEM learning. Designing AI tutors, IoT sensor networks, and data-rich dashboards."
email: selcukinc@tamu.edu
# baseurl: "" # keep this blank
# url: "https://selcuklnc.github.io" # keep this blank

# Social Media Profiles
twitter_username: # Buraya Twitter kullanıcı adınızı yazın (varsa)
github_username:  selcuklnc
linkedin_username: "selcukkilinc"
scholar:
  style: apa # Google Scholar linklerinizin formatı
  source: "https://scholar.google.com/citations?user=YOUR_USER_ID" # Google Scholar profil linkinizi buraya ekleyin
research_gate_profile: "Selcuk-Kilinc-4" # ResearchGate profil linkinizdeki kullanıcı adınız

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Collections
collections:
  portfolio:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  teaching:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# SASS/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-include-cache

# Pug
pug:
  # کامپایل کردن فایل‌های پوگ
  # minify: true
  # source: _pug
  # destination: .
